### ISSUE TITLE
ascii-art problem

### ISSUE THREAD

**Issue by andreymaznyak** [pleerock/microframework#4]
Hi, i have problem, when install dependencies. I can't install ascii-art module, becouse it require MS BUILD tools. Please remove this dependency.

**Comment by andreymaznyak** [comment]
I want to help develop this framework.

**Comment by pleerock** [comment]
Hi. 

> becouse it require MS BUILD tools

why? what is MS BUILD tools? 

> I want to help develop this framework.

thats great, start with ideas what you want to implement in this framework

**Comment by pleerock** [comment]
feel free to reopen it if you are still interested in this issue.
